Exception during training: Return Code: 1, CMD: ['/usr/local/bin/python', 'mnist_keras_tf20_eager.py', '--model-dir', '/opt/ml/model'], Err: b'Using TensorFlow backend.\nWARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.\nYou should consider upgrading via the \'pip install --upgrade pip\' command.\nTraceback (most recent call last):\n  File "mnist_keras_tf20_eager.py", line 86, in <module>\n    x_train = np.load(os.path.join(training_dir, \'training.npz\'))[\'image\']\n  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 428, in load\n    fid = open(os_fspath(file), "rb")\nFileNotFoundError: [Errno 2] No such file or directory: \'/home/ec2-user/SageMaker/jsimon-mnist/train/local-test/test_dir/data/training.npz\'\n'
Traceback (most recent call last):
  File "/opt/program/train", line 71, in <module>
    _run(train_cmd)
  File "/opt/program/train", line 39, in _run
    raise Exception(error_msg)
Exception: Return Code: 1, CMD: ['/usr/local/bin/python', 'mnist_keras_tf20_eager.py', '--model-dir', '/opt/ml/model'], Err: b'Using TensorFlow backend.\nWARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.\nYou should consider upgrading via the \'pip install --upgrade pip\' command.\nTraceback (most recent call last):\n  File "mnist_keras_tf20_eager.py", line 86, in <module>\n    x_train = np.load(os.path.join(training_dir, \'training.npz\'))[\'image\']\n  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 428, in load\n    fid = open(os_fspath(file), "rb")\nFileNotFoundError: [Errno 2] No such file or directory: \'/home/ec2-user/SageMaker/jsimon-mnist/train/local-test/test_dir/data/training.npz\'\n'
